#! /bin/bash

# Author: Mohammed Albatati
# Date: 14 Sep 2021
# Get the Asset and crew details using fzf and case to get the option to do what you need
# Modified : 19 Sep 21
# Modification: added the ability to get generate the csv file from the excel sheet and put it in the temp directory

set -e
# Ensure the asset csv file is available and if not then create it 
[ ! -f "/tmp/assetID.csv" ] && echo 'File not available at temp directory  Creating a new csv file' && xlsx2csv "/Users/mohammedalbatati/Desktop/FAR Master list REV2.xlsx" "/tmp/assetID.csv" 
[ ! -f "/tmp/crewID.csv" ] && echo 'File not available at temp directory  Creating a new csv file' && xlsx2csv "/Users/mohammedalbatati/Documents/OilSERV files/Personnel/Compensation/Master Calculation sheet/Reference files/ref.xlsx" "/tmp/crewID.csv" 

fzfID(){
	grepID= awk -F"," '{print $1"|"$2"|"$3"|"$4"|"$5"|"$6"|"$9"|"$10"|"$11"|"$12"|"$13"|"$14"|"$15"|"$15"|"$16}' "/tmp/assetID.csv" | fzf -m
	echo $grepID
}

fzfCrew(){
	grepID= awk -F"," '{print $0}' "/tmp/crewID.csv" | fzf -m
	# grepID= awk -F"," '{print $1"|"$2"|"$3"|"$4"|"$7}' "/tmp/crewID.csv" | fzf -m
	echo $grepID
}

echo "Type 1) Asset 2) Crew"
read -p "Select: " num
echo "==========="
case $num in 
  1) fzfID;;
  2) fzfCrew;;
  *) echo "Wrong selection";;
esac

